name: Unity CI (com testes e build)

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

env:
  UNITY_VERSION: 2022.3.13f1
  PROJECT_PATH: .

jobs:
  unity-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.1

      - name: Cache Library
        uses: actions/cache@v4.2.3
        with:
          path: ${{ env.PROJECT_PATH }}/Library
          key: Library-${{ env.PROJECT_PATH }}-${{ env.UNITY_VERSION }}-${{ hashFiles('**/Packages/manifest.json') }}
          restore-keys: |
            Library-${{ env.PROJECT_PATH }}-${{ env.UNITY_VERSION }}-
            Library-

      - name: Run PlayMode Tests
        id: tests
        uses: game-ci/unity-test-runner@v4.3.1
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          testMode: playmode
          artifactsPath: TestResults

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4.6.2
        with:
          name: Unity-PlayMode-Tests
          path: ${{ steps.tests.outputs.artifactsPath }}

      - name: Build Project (StandaloneWindows64)
        id: build
        uses: game-ci/unity-builder@v4.5.0
        env:
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          projectPath: ${{ env.PROJECT_PATH }}
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows64

      - name: Upload Build
        uses: actions/upload-artifact@v4.6.2
        with:
          name: UnityBuild-Windows
          path: ${{ steps.build.outputs.buildPath }}
